# Site settings
author: Jon Schacter
title: Jon Schacter
header-img: img/home-bg.png
email: schacter.jon@gmail.com
copyright_name: Jon Schacter
description: > # this means to ignore newlines until "baseurl:"
  A New Coders Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jonschacter

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
